### ISSUE TITLE
Review bugs

### ISSUE THREAD

**Issue by fahimy143** [for-ashraf/Portfolio#11]
Hi @for-ashraf 
Your code is complete just you forget to add this code at the end of your codes 
contactForm.addEventListener('submit', logSubmit);
without this your code will not have any behavior. 

![](https://media.giphy.com/media/AiF8ZsTESrDwRjEcIU/giphy.gif)

cheers and happy coding

**Comment by for-ashraf** [comment]
Thank you very much for creating the issues to improve my productivity. In this regard, it is stated that I have solved the following issue:
I have triggered the event.
