### ISSUE TITLE
Peer to peer review issue. 

### ISSUE THREAD

**Issue by wadaudzai** [for-ashraf/Portfolio#7]
Dear Mohammad Ashraf,

Good work on the project and I appreciate how much you effort you've put into this project. However, we have some suggestions that we would like to share with you.
- [ ]  It would be better to merge the last pull request. As far as it's approved.
- [ ] You still have some room for improvement according to the figma template.

**Comment by for-ashraf** [comment]
Thank you very much for creating the issues to improve my productivity. In this regard, it is stated that I have solved the following two issues:
I have merged the last pull request
The design is now according to the Figma design template
